export const MENSAJES_APP = {
    formCamposVacios: "Debe digitar o seleccionar los campos del formulario.",
    formValoresDiferentes: "Debe seleccionar valores diferentes al inicial.",
    mensajeConfirmDelete: "¿Esta seguro de eliminar el elemento seleccionado?",
    mensajeConfirmSave: "¿Esta seguro de registrar la información?",
    errorServidor: "Se ha producido un error inesperado en el servidor.",
    errorConnectionRefusedServer: "Se ha enviado la petición pero el servidor no responde.",
    cargandoPeticion: "Se ha enviado la petición al servidor, por favor espere.",
    formularioIncompleto: "El formulario se encuentra incompleto por favor digite todos los campos.",
    tituloError: "Error en la petición",
    tituloSuccess: "Exito en la petición",
    tituloAlerta: "Procesando Petición",
    JSON_PARSE_ERROR: "ERROR AL PARSEAR EL JSON STRING",
    accionAceptar: "Aceptar",
    accionCancelar: "Cancelar",
    errorAccesoEvaluacionNoPermitido: "Se modifico la información del expediente se debe actualizar.",
    existeArchivoJsonEnLista: "El archivo seleccionado se encuentra en la lista.",
    usuarioNoTienePermisos: "No cuentas con los permisos necesarios para ingresar a este recurso, contacta al administrador.",
    tamanoArchivoSuperado: "Se ha superado el tamaño maximo permitido ",
    contrasenasDiferentes: "Las contraseñas deben ser iguales.",
    beneficiarioNoEliminado: "No puede eliminar el unico beneficiario.",
    tituloAlertaExitoso: "Registro Exitoso",
    mensajeCargaInfo: "Se cargo la información con éxito"
}